name: Run Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use your project's Node version
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          NODE_ENV: ci
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: npx mocha --exit  








